source 'https://rubygems.org'

ruby '2.7.1'

gem 'bundler', '~> 2.0'

# Minor Utils/helpers
gem 'amazing_print', '~> 1.2.1'
gem 'rainbow', '~> 3.0.0'
gem 'chronic', '~> 0.10.2'
gem 'chunky_png', '~> 1.3.11'

